name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix build

      - name: Run tests in dev shell
        run: |
          nix develop --command bash -c '
            poetry install
            poetry run pytest
          '

      - name: Check formatting
        run: |
          nix develop --command bash -c '
            poetry install
            poetry run black --check example_app tests
            poetry run isort --check example_app tests
          '

      - name: Run linting
        run: |
          nix develop --command bash -c '
            poetry install
            poetry run pylint example_app tests
          ' 
